  name: TESTAPI
  on:
    push:
      branches:
        - 'main'
        - 'master'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Push repo
          uses: actions/checkout@v3
        - name: Print hello
          run: echo 'Hello Raja'